version: '3.8' 

services:
  eureka-service:
    image: eureka-service:0.0.1-SNAPSHOT
    ports:
      - "8761:8761" 
    environment:
      EUREKA_INSTANCE_HOSTNAME: eureka-service
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: 'false'
      EUREKA_CLIENT_FETCH_REGISTRY: 'false'

  cambio-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cambio_db

  cambio-service:
    image: cambio-service:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cambio-db:5432/cambio_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    depends_on:
      - cambio-db
      - eureka-service
    deploy:
      replicas: 2  
  produto-db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: produto_db

  produto-service:
    image: produto-service:0.0.1-SNAPSHOT
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://produto-db:5432/produto_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    depends_on:
      - produto-db
      - eureka-service

  api-gateway-service:
    image: api-gateway-service:0.0.1-Mri
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-service:8761/eureka
    ports:
      - "8770:8765" # Mudei a porta mapeada para 8770
    depends_on:
      - cambio-service
      - produto-service
      - eureka-service