server:
  port: 8000

spring:
  application:
    name: produto-service
  datasource:
    url: jdbc:postgresql://localhost/produto_db_b
    username: postgres
    password: Alemao17
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format-sql: true
    show-sql: true
  flyway:
    locations:
    - classpath:/db_migration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
endpoint:
  health:
    show-details: always